# Generated by Django 4.2.20 on 2025-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование:')),
                ('description', models.TextField(verbose_name='Описание/текст')),
                ('time', models.IntegerField(default=10, verbose_name='Време за приготвяне')),
                ('category', models.CharField(default='', max_length=100, verbose_name='Категория')),
                ('picture', models.ImageField(upload_to='pictures/', verbose_name='Снимка:')),
                ('attachment', models.FileField(upload_to='files/', verbose_name='Файл')),
            ],
        ),
    ]
